site_name: AWS MCP Servers
site_url: https://awslabs.github.io/mcp
theme:
  name: material
  logo: images/logo.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
plugins:
  - search
  - include-markdown
nav:
  - Home: index.md
  - AWS MCP Servers:
    - Core MCP Server: servers/core-mcp-server.md
    - CDK MCP Server: servers/cdk-mcp-server.md
    - Nova Canvas MCP Server: servers/nova-canvas-mcp-server.md
    - Bedrock Knowledge Base Retrieval MCP Server: servers/bedrock-kb-retrieval-mcp-server.md
    - Cost Analysis MCP Server: servers/cost-analysis-mcp-server.md

