site_name: AWS MCP Servers
site_url: https://awslabs.github.io/mcp

repo_name: 'awslabs/mcp'
repo_url: 'https://github.com/awslabs/mcp'
copyright: '&copy; Amazon Web Services, Inc. or its affiliates. All rights reserved.'

theme:
  name: material
  logo: images/logo.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
  palette:
    # Palette toggle for light mode
    - scheme: dracula
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - privacy
  - search
  - include-markdown
nav:
  - Home: index.md
  - AWS MCP Servers:
    - Amazon MQ MCP Server: servers/amazon-mq-mcp-server.md
    - AWS SNS SQS MCP Server: servers/amazon-sns-sqs-server.md
    - Core MCP Server: servers/core-mcp-server.md
    - Amazon Bedrock Knowledge Base Retrieval MCP Server: servers/bedrock-kb-retrieval-mcp-server.md
    - AWS CDK MCP Server: servers/cdk-mcp-server.md
    - Cost Analysis MCP Server: servers/cost-analysis-mcp-server.md
    - Amazon Nova Canvas MCP Server: servers/nova-canvas-mcp-server.md
    - AWS Documentation MCP Server: servers/aws-documentation-mcp-server.md
    - AWS Lambda Tool MCP Server: servers/lambda-tool-mcp-server.md
    - AWS Diagram MCP Server: servers/aws-diagram-mcp-server.md
    - AWS Step Functions Tool MCP Server: servers/stepfunctions-tool-mcp-server.md
    - AWS Terraform MCP Server: servers/terraform-mcp-server.md
    - Git Repo Research MCP Server: servers/git-repo-research-mcp-server.md
    - CloudFormation MCP Server: servers/cfn-mcp-server.md
    - AWS Serverless MCP Server: servers/aws-serverless-mcp-server.md
    - Finch MCP Server: servers/finch-mcp-server.md
    - Amazon EKS MCP Server: servers/eks-mcp-server.md
    - Amazon ECS MCP Server: servers/ecs-mcp-server.md
    - AWS Support MCP Server: servers/aws-support-mcp-server.md
  - Samples:
    - Home: samples/index.md
    - MCP Integration with Amazon Bedrock Knowledge Bases: samples/mcp-integration-with-kb.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
