name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5b8a807627bf8 #v4.6.0
        with:
          deny-licenses: |
            AGPL-1.0,AGPL-1.0-only,AGPL-1.0-or-later,AGPL-3.0,AGPL-3.0-only,AGPL-3.0-or-later,
            AML,
            CDLA-Sharing-1.0,
            CPAL-1.0,
            MIT-enna,
            EUPL-1.1,EUPL-1.2,
            LGPL-3.0+,LGPL-3.0,LGPL-3.0-only,LGPL-3.0-or-later,
            GPL-3.0-only,GPL-3.0-or-later,GPL-3.0,GPL-3.0+,GPL-3.0-with-autoconf-exception,GPL-3.0-with-GCC-exception,
            NASA-1.3,
            ODbL-1.0,
            OSL-3.0,
            Parity-7.0.0,
            RPSL-1.0,
            SSPL-1.0
          ## Honest Public License (HPL) 1.0
