name: pre-commit

on:
  pull_request:
  push:
    branches: [main]
permissions: read-all
jobs:
  detect-precommit:
    runs-on: ubuntu-latest
    outputs:
      precommits: ${{ steps.find-precommit.outputs.precommits }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Find precommit configurations
        id: find-precommit
        working-directory: .
        run: |
          PRECOMMITS=$(find . -name ".pre-commit-config.yaml" -exec dirname {} \; | sed 's/^\.\///' | jq -R -s -c 'split("\n")[:-1]')
          echo "precommits=$PRECOMMITS" >> $GITHUB_OUTPUT

  pre-commit:
    needs: [detect-precommit]
    if: ${{ needs.detect-precommit.outputs.precommits != '[]' && needs.detect-precommit.outputs.precommits != '' }}
    strategy:
      fail-fast: false
      matrix:
        precommit: ${{ fromJson(needs.detect-precommit.outputs.precommits) }}
    name: Precommit ${{ matrix.precommit }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.precommit }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5.6.0
      with:
        python-version-file: ${{ matrix.precommit }}/.python-version
    - run: |
        python -m pip install pre-commit
        python -m pip freeze --local
    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 #v4.2.3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ runner.os }}|${{ hashFiles(matrix.precommit) }}
    - run: pre-commit run --show-diff-on-failure --color=always --all-files
      working-directory: ${{ matrix.precommit }}
